### ISSUE TITLE
Error reading from database

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-qtype_shortmath#21]
A ShortMath question appears to be successfully created, and displays in the question bank. However, in the JazzQuiz editor, we get an error message upon reading the database. I have seen the behaviour before, but I cannot remember where.  It may be a permissions issue. 
If I remember correctly, that this is a permissions issue, it may be triggered by recent updates to moodle, and not to changes in our plugins.

**Comment by hgeorgsch** [comment]
Correction. Preview fails also from the question bank. Listing, however, works in the question bank but fails in JazzQuiz.

**Comment by andstor** [comment]
This has most likely to do with the renaming of the DB table and the removal of some unnecessary fields.

Replacing the [upgrade.php](https://github.com/KQMATH/moodle-qtype_shortmath/blob/develop/db/upgrade.php) file in the db folder in the plugin, with this attached file [upgrade.php.zip](https://github.com/KQMATH/moodle-qtype_shortmath/files/2480755/upgrade.php.zip), and upping the version number should do the trick.

Alternatively, one could reinstall the plugin.
