### ISSUE TITLE
Finish CHANGELOG

### ISSUE THREAD

**Issue by andstor** [KQMATH/moodle-qtype_shortmath#24]
The [CHANGELOG.md](https://github.com/KQMATH/moodle-mod_capquiz/blob/development/CHANGELOG.md) file should be completed.

The format is based on [Keep a Changelog](
https://keepachangelog.com/en/1.0.0).

**Comment by hgeorgsch** [comment]
Can we close this, @andstor ?
It looked ok to me ...

**Comment by hgeorgsch** [comment]
We have forgotten the history so it is too late to record now.  Last two versions are OK.
