### ISSUE TITLE
Can't backup or duplicate quizzes with ShortMath Questions

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-qtype_shortmath#33]
This was posted on the Moodle site.

   There is a problem with ShortMath questions. I don't know if it is a
   problem that my administrator can solve or not (I already contacted) but I
   post the problem here too.

   I can't duplicate quizzes with a ShortMath question (dmlreadexception
   error). The problem is that I also can't make a course backup with the
   question bank (same error).

   Does anyone know how to solve it? I want to help my administrator with
   some information about it.

**Comment by hgeorgsch** [comment]
@nan-hk Can you test and verify this bug?

**Comment by hgeorgsch** [comment]
New question about this bug today: https://moodle.org/plugins/qtype_shortmath

**Comment by nan-hk** [comment]
Yes, I will do it now.
Best Regards,
Nan Hom Kham


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
