### ISSUE TITLE
Wrong path in define call.

### ISSUE THREAD

**Issue by andstor** [KQMATH/moodle-qtype_shortmath#4]
In the input.js file, in the define function call, the path should be ```qtype_shortmath/visual-math-input```, not ```plugin_name/visual-math-input```.

**Comment by hgeorgsch** [comment]
On Wed, Sep 05, 2018 at 07:20:53AM -0700, André Storhaug wrote:
> The path should be ```qtype_shortmath/visual-math-input```, not ```plugin_name/visual-math-input```.

Silly me.  It is not enough, though.
It still does not work.

-- 
:-- Hans Georg
