### ISSUE TITLE
Admin navigation override error

### ISSUE THREAD

**Issue by Kemmotar83** [KQMATH/moodle-qtype_shortmath#63]
Hi,

I'm using Moodle 3.10 and I've just updated your plugin to the latest version (2021080200) and now, entering any admin page, the navigation is set to Shortmath admin page.

1. Go to 'Site administration'
2. Click on any page (ie. Analytics -> Site information)
3. See the breadcrumb

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3964915/128154591-7d1b7d7c-16b1-42be-8441-066b4bd678ca.png)

I've checked the code and this behavior seems to be related to file _setting.php_, where in line 29 you set PAGE URL ( $PAGE->set_url('/admin/settings.php', ['section' => 'qtypesettingshortmath']); ). As I know, this file is loaded every time, so you always override PAGE URL.

Thanks,
Giorgio

**Comment by andstor** [comment]
Thanks @Kemmotar83 🙏 
This was something that slipped through our testing 😅 

New release coming up shortly!

**Comment by andstor** [comment]
@Kemmotar83 new release [v1.0.1](https://moodle.org/plugins/qtype_shortmath/1.0.1/24863) should resolve this bug 😄

**Comment by Kemmotar83** [comment]
Thank you for this quick update.

Giorgio
